### ISSUE TITLE
license perhaps?

### ISSUE THREAD

**Issue by SignpostMarv** [VerbalExpressions/verbalExpressions.github.io#1]
Tinkering around with the code to bring the page speed insights scores up, no license however- would possibly need one posted to make the pull request ?

**Comment by SignpostMarv** [comment]
Compare: [original as of time of writing](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fverbalexpressions.github.io%2F&tab=mobile) vs [modified as of time of writing](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdev.signpostmarv.name%2Fpub%2Fverbalexpressions.github.io%2F&tab=mobile)

**Comment by jehna** [comment]
I'd just slap a MIT license and call it a day. Is that OK for @ionutvmi?

**Comment by mihai-vlc** [comment]
The MIT license was added.
@SignpostMarv that looks awesome :+1:

**Comment by SignpostMarv** [comment]
Thanks! pull request is up now #2 :)
